Fica em /usr/local/bin/backup_mariadb.sh

crontab -e

0 0 * * * /usr/local/bin/backup_mariadb.sh > /var/log/backup_mariadb.log 2>&1

Altere o user e senha do banco nos campos DB_USER e DB_PASSWORD


#!/bin/bash

# Configurações do banco de dados
DB_USER=""
DB_PASSWORD=""
DB_NAME="nuvdesk"
BACKUP_DIR="/var/www/html/nuvdesk/nuvdesk/storage/app/public/backup"
DATE=$(date +%Y-%m-%d_%H-%M-%S)
BACKUP_FILE="backup_$DATE.sql"
BACKUP_PATH="$BACKUP_DIR/$BACKUP_FILE"

# Cria o diretório de backup, caso não exista
mkdir -p "$BACKUP_DIR"

# Executa o backup usando o mysqldump
mysqldump -u $DB_USER -p$DB_PASSWORD $DB_NAME > "$BACKUP_PATH"

# Verifica se o backup foi realizado com sucesso
if [ $? -eq 0 ]; then
    STATUS="sucesso"
    echo "Backup realizado com sucesso em $BACKUP_PATH"
else
    STATUS="falha"
    echo "Falha ao realizar o backup."
fi

# Insere o registro no banco de dados indicando o status do backup e seu caminho
mysql -u $DB_USER -p$DB_PASSWORD $DB_NAME -e "INSERT INTO backups (data_hora, local_arquivo, status, created_at) VALUES (NOW(), '$BACKUP_PATH', '$STATUS', NOW());"

# Remove backups antigos (opcional) - mantém apenas os últimos 7 dias
find "$BACKUP_DIR" -type f -name "*.sql" -mtime +7 -exec rm {} \; -exec mysql -u $DB_USER -p$DB_PASSWORD $DB_NAME -e "DELETE FROM backups WHERE local_arquivo='{}';" \;
